In [1]:
import numpy as np

In [8]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
zero[4]=1
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.92475867 0.02248477 0.64973904]
  [0.31564416 0.18713056 0.92089965]
  [0.87735761 0.47998401 0.32419447]]

 [[0.05242499 0.73758784 0.69560112]
  [0.81852181 0.99793908 0.33632507]
  [0.21153847 0.94440747 0.2407844 ]]

 [[0.32242358 0.20799446 0.61011068]
  [0.57898639 0.34617711 0.1210686 ]
  [0.70860213 0.37623868 0.83172108]]]


In [18]:
arr = np.random.randint(1, 9, size =(3, 3, 3))
print(arr)

[[[7 8 7]
  [1 5 4]
  [5 1 6]]

 [[3 5 7]
  [8 8 3]
  [7 6 3]]

 [[1 2 8]
  [6 1 2]
  [1 4 5]]]


In [22]:
#전체요소가 30인 numpy 배열 만들기
arr = np.random.random(30)
print(arr)
#그 배열의 평균값 구하기
print(np.mean(arr))

[0.22309204 0.36474986 0.63615801 0.94344061 0.92740938 0.31663328
 0.03030132 0.05449921 0.40158836 0.48274732 0.04439324 0.31846771
 0.05057164 0.75235815 0.60107505 0.48110012 0.38312126 0.73581456
 0.69090487 0.00176197 0.5833556  0.54863349 0.45766125 0.4144227
 0.42677036 0.28979333 0.35877177 0.03146245 0.84790779 0.08400427]
0.41609903283449845


In [23]:
mid_score = [10, 20, 30]
final_score = [70, 80, 90]
total_list = []
total_list = mid_score+final_score
#리스트로는 계산을 할 수 없음
print(total_list)


[10, 20, 30, 70, 80, 90]


In [24]:
#리스트를 계산하기 위해선 numpy필요
import numpy as np

In [30]:
mid_score = np.array([10, 20, 30])
final_score = np.array([70, 80, 90])

total_numpy = mid_score + final_score
avg = total_numpy / 2

print("시험 성적의 합계: ", total_numpy)
#print("시험 성적의 합계: ", total_numpy/2)
print("시험 성적의 평균: ", avg)

시험 성적의 합계:  [ 80 100 120]
시험 성적의 평균:  [40. 50. 60.]


In [38]:
#array_a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_a = []
for i in range(10):
    arr_a.append(i)
array_a = np.array(arr_a)
print(array_a)
#array_a = np.arange(0, 10)
#print(array_a)

#array_b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array_b = np.arange(10)
print(array_b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [40]:
#array_c = [0, 2, 4, 6, 8]
array_c = np.arange(0, 10, 2)
print(array_c)
print(array_c.shape)
print(array_c.ndim)

#byte크기
print(array_c.dtype)
print(array_c.size)

#배열 내의 원소 크기를 바이트 단위로 알려줌: 4byte
print(array_c.itemsize)

[0 2 4 6 8]
(5,)
1
int32
5
4


In [47]:
salary = np.array([220, 250, 230])
salary = salary + 100
print("100추가: ", salary)
salary = salary * 2
print("월급이 2배: ", salary)

100추가:  [320 350 330]
월급이 2배:  [640 700 660]


In [64]:
players = [[170, 76.4], [183, 86.2], [171, 73.5], [176, 80.1]]

np_players=np.array(players)
print(np_players)

#몸무게가 80kg이상인 선수만 출력
#                                                            행 열
print("몸무게가 80이상인 선수의 정보: ", np_players[np_players[:, 1] >= 80.0])

#키가 180이상인 선수만 출력
#                                                         행 열
print("키가 180이상인 선수의 정보: ", np_players[np_players[:, 0] >= 180.0])


[[170.   76.4]
 [183.   86.2]
 [171.   73.5]
 [176.   80.1]]
몸무게가 80이상인 선수의 정보:  [[183.   86.2]
 [176.   80.1]]
키가 180이상인 선수의 정보:  [[183.   86.2]]
