In [1]:
import numpy as np

In [8]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
zero[4]=1
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.92475867 0.02248477 0.64973904]
  [0.31564416 0.18713056 0.92089965]
  [0.87735761 0.47998401 0.32419447]]

 [[0.05242499 0.73758784 0.69560112]
  [0.81852181 0.99793908 0.33632507]
  [0.21153847 0.94440747 0.2407844 ]]

 [[0.32242358 0.20799446 0.61011068]
  [0.57898639 0.34617711 0.1210686 ]
  [0.70860213 0.37623868 0.83172108]]]


In [18]:
arr = np.random.randint(1, 9, size =(3, 3, 3))
print(arr)

[[[7 8 7]
  [1 5 4]
  [5 1 6]]

 [[3 5 7]
  [8 8 3]
  [7 6 3]]

 [[1 2 8]
  [6 1 2]
  [1 4 5]]]


In [22]:
#전체요소가 30인 numpy 배열 만들기
arr = np.random.random(30)
print(arr)
#그 배열의 평균값 구하기
print(np.mean(arr))

[0.22309204 0.36474986 0.63615801 0.94344061 0.92740938 0.31663328
 0.03030132 0.05449921 0.40158836 0.48274732 0.04439324 0.31846771
 0.05057164 0.75235815 0.60107505 0.48110012 0.38312126 0.73581456
 0.69090487 0.00176197 0.5833556  0.54863349 0.45766125 0.4144227
 0.42677036 0.28979333 0.35877177 0.03146245 0.84790779 0.08400427]
0.41609903283449845
