#### Numpy라이브러리 활용해보기
- 고성능의 계산을 하고 싶을 때 사용한다

In [3]:
import numpy as np

##### 1차원

In [42]:
#방법2-변수활용해서 넣기
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [43]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [37]:
#방법2-직접넣기
arr1 = np.array([1,2,3,4,5])
print(arr1)
#배열의 형태 확인
print(arr1.shape)
#배열의 크기 확인
print(arr1.size)
#
print(arr1.dtype)
#몇차원인지 확인
print(arr1.ndim)

[1 2 3 4 5]
(5,)
5
int32
1


##### 2차원

In [36]:
#               동일한 원소개소 유지 [], [] -> 같은 차원인 경우
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int32
2


##### 3차원 배열

In [32]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 3, 5],[2, 4, 6]], [[7, 8, 9], [9, 8, 7]]])
print(arr3)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 3 5]
  [2 4 6]]

 [[7 8 9]
  [9 8 7]]]
(3, 2, 3)
18
int32
3


In [31]:
arr3_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8],]])
print(arr3_1)
print(arr3_1.shape)
print(arr3_1.size)
print(arr3_1.dtype)
print(arr3_1.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
8
int32
3


In [34]:
#3*4인형태인 모든 값이 0으로 채워진 배열 만들기
arr_zeros = np.zeros((3, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#3*4인형태인 모든 값이 1으로 채워진 배열 만들기
arr_ones = np.ones((3, 4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
#원하는 값 지정해서 원하는 형태의 배열만들기
arr_full = np.full((3,2), 5)
arr_full

array([[5, 5],
       [5, 5],
       [5, 5]])

In [40]:
#for문 이용해서 1~50이 들어간 리스트 만들기
list = []
for i in range(1, 51):
    list.append(i)
print(list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [44]:
arr = np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [46]:
#1~50이 담긴 배열 생성하기
arr = np.arange(1, 51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [47]:
#               범위   단위    
arr = np.arange(1, 51, 10)
arr

array([ 1, 11, 21, 31, 41])

In [50]:
#랜덤 값 배열 생성하기-rand: 실수
arr = np.random.rand(2, 3)
arr

array([[0.37022336, 0.52963671, 0.51134964],
       [0.99979379, 0.47027249, 0.3393414 ]])

In [51]:
#랜덤 값 배열 생성하기-randint: 정수
arr = np.random.randint(2, 10)
arr

6

In [52]:
arr = np.random.randint(2, 10, size=(2, 3))
arr

array([[2, 3, 7],
       [7, 9, 2]])

In [53]:
#타입 지정하여 배열 생성하기-int32? / 실수 -> int64 / 정수
arr_type = np.array([1.1, 2.2, 3.3], dtype = np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [54]:
#타입변경하기                실수 비트
arr_type = arr_type.astype("float64")
arr_type

array([1., 2., 3.])

In [55]:
arr_type.dtype

dtype('float64')

##### 연산

In [57]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [58]:
arr + arr

array([2, 4, 6])

In [59]:
arr * arr

array([1, 4, 9])

In [60]:
#1차원 배열
arr_a = np.array([1,2,3])
arr_a

array([1, 2, 3])

In [61]:
arr_b = np.array([4, 5, 6])
arr_b

array([4, 5, 6])

In [62]:
arr_a + arr_b

array([5, 7, 9])

In [64]:
#2차원
arr2_a = np.array([[1, 2, 3], [4, 5, 6]])
arr2_a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr2_a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [65]:
arr2_b = np.array([[[7, 8, 9],[10, 11, 12]]])
arr2_b

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr2_b * 2

array([[[14, 16, 18],
        [20, 22, 24]]])

In [71]:
arr2_a + arr2_b

array([[[ 8, 10, 12],
        [14, 16, 18]]])

##### 인덱싱, 슬라이싱

##### 1차원 인덱싱

In [86]:
arr1 = np.array([0, 1, 2, 3, 4, 5])
arr1

array([0, 1, 2, 3, 4, 5])

In [87]:
print(arr1[2])
print(arr1[5])

2
5


##### 2차원 인덱싱

In [90]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
print(arr2[0])
print(arr2[0][0])
print('-----------')
print(arr2[1][0])
print(arr2[1][2])
print(arr2[1, 2])
print(arr2[1])

[1 2 3]
1
-----------
4
6
6
[4 5 6]


##### 슬라이싱

##### 1차원 슬라이싱

In [95]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
#3부터 8미만
arr1[3:8]

array([3, 4, 5, 6, 7])

In [98]:
#슬라이싱한 곳에 데이터 넣기
arr1[3:8] = 12
arr1

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

##### 2차원 슬라이싱

In [101]:
arr2 = np.arange(50).reshape(5, 10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
#0행부터 1행까지 전체 열 출력
arr2[:2, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [110]:
#전체 행의 1열만 출력
arr2[:, 0]

array([ 0, 10, 20, 30, 40])

In [113]:
#0행부터 3행까지 0열부터 4열까지 출력
arr2[:4, 0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [116]:
#21출력-인덱싱 사용
arr2[2, 1]
#arr2[2][1]
#arr2[2:3, 1:2]

21

In [119]:
print(arr2[4, 8])
print(arr2[2, 9])
print(arr2[1, 2])

48
29
12


##### boolean

In [124]:
score = np.array([80, 75, 55, 96, 30])
print(score)
print(score >= 80)
print(score[score>=80])

[80 75 55 96 30]
[ True False False  True False]
[80 96]


In [125]:
name = np.array(["영화", "동원", "성우", "수민"])
name

array(['영화', '동원', '성우', '수민'], dtype='<U2')

In [126]:
bol = np.array([False, True, False, True])
bol

array([False,  True, False,  True])

In [127]:
name[bol]

array(['동원', '수민'], dtype='<U2')