#### Numpy라이브러리 활용해보기

In [3]:
import numpy as np

##### 1차원

In [42]:
#방법2-변수활용해서 넣기
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [43]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [37]:
#방법2-직접넣기
arr1 = np.array([1,2,3,4,5])
print(arr1)
#배열의 형태 확인
print(arr1.shape)
#배열의 크기 확인
print(arr1.size)
#
print(arr1.dtype)
#몇차원인지 확인
print(arr1.ndim)

[1 2 3 4 5]
(5,)
5
int32
1


##### 2차원

In [36]:
#               동일한 원소개소 유지 [], [] -> 같은 차원인 경우
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int32
2


##### 3차원 배열

In [32]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 3, 5],[2, 4, 6]], [[7, 8, 9], [9, 8, 7]]])
print(arr3)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 3 5]
  [2 4 6]]

 [[7 8 9]
  [9 8 7]]]
(3, 2, 3)
18
int32
3


In [31]:
arr3_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8],]])
print(arr3_1)
print(arr3_1.shape)
print(arr3_1.size)
print(arr3_1.dtype)
print(arr3_1.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
8
int32
3


In [34]:
#3*4인형태인 모든 값이 0으로 채워진 배열 만들기
arr_zeros = np.zeros((3, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#3*4인형태인 모든 값이 1으로 채워진 배열 만들기
arr_ones = np.ones((3, 4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
#원하는 값 지정해서 원하는 형태의 배열만들기
arr_full = np.full((3,2), 5)
arr_full

array([[5, 5],
       [5, 5],
       [5, 5]])

In [40]:
#for문 이용해서 1~50이 들어간 리스트 만들기
list = []
for i in range(1, 51):
    list.append(i)
print(list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [44]:
arr = np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])